### ISSUE TITLE
Enhancements: lighter tooltips and separator lines in list views?

### ISSUE THREAD

**Issue by mbacou** [adapta-project/adapta-gtk-theme#260]
**Reporter info**
 * Ubuntu 16.10 -
 * Gtk+ 3.0 version -
 * Gnome 3.20 

**Adapta version (if you knew)**
3.22

**Related Application and/or Shell theming (or name of widget)**
Nautilus
Tooltips

**Other Note (feature-request, question, etc...)**
This is truly excellent work, just would just like to suggest 2 small variations to the heme for usability:

1) Separator lines in list views, esp. in Nautilus:

current:
![screenshot from 2016-10-23 20-15-12](https://cloud.githubusercontent.com/assets/260325/19630689/76e7d88a-995d-11e6-84e7-04f4e35712c6.png)

list views are easier on the eye with very light separators, e.g. in Thunderbird:
![screenshot from 2016-10-23 20-09-56](https://cloud.githubusercontent.com/assets/260325/19630659/ba54a22a-995c-11e6-9a1d-08cbaed3b44c.png)

2) I generally find the **white on black tooltips** too harsh, would prefer the usual semi-transparent yellow background and dark text. Wonder if others agree...

**Comment by tista500** [comment]
Please read these first:
https://material.google.com/components/lists.html#
https://material.google.com/components/tooltips.html#

> 1) Separator lines in list views, esp. in Nautilus:

Hmm, we've already add hovered fill-area and highlight labels in single-line row. isn't it enough?
In Material design, Guidelines should describe about "multi-column" rows as well though, but at least I don't think we need horizontal separators between such rows. For example, Adapta tweaks Corebird's list-view with asymmetric horizontal separators between tweets. Because those rows had "multi-lines" inside the single-rows.

And as your 2nd shot, your shot explains TreeView instead of list-view. TreeView has cascading child sub-rows (revealer). Their clickable actions are different with list-view and should not be confused them.

> 2) I generally find the white on black tooltips too harsh, would prefer the usual semi-transparent yellow background and dark text. 

I'm afraid that you were estimating only just for light-variant. Yellow backgrounds in dark-variant? Oh no, please... 

Regards.

**Comment by mbacou** [comment]
On the tooltips, yes only for the light-variant of Adapta.
On the list-views, hovered fill-area and highlight labels are nice, but separators are eye-friendly when scanning long list of files for last accessed/changed dates, etc...

**Comment by tista500** [comment]
> separators are eye-friendly when scanning long list of files for last accessed/changed dates, etc...

I don't think so.
![screenshot from 2016-10-24 16-13-01](https://cloud.githubusercontent.com/assets/6073622/19636642/7e2857ac-9a05-11e6-9da9-851a91e63718.png)

Those horizontal separators can not be "illusion-blocker" but just "afterimage", especially if you changed zoom-level to 50%. And after researching some other file-managers and Gtk+ themes, there were few chance to see those horizontal separators (Greybird had such things). I think those separators will cause the eye-stress in case we scrolled vertically up/down quickly, since light and dark are very frequently repeated in very short time period.

Finally I won't apply your suggestions.

Regards.
