### ISSUE TITLE
Adapta theme for Plymouth?

### ISSUE THREAD

**Issue by igor-dyatlov** [adapta-project/adapta-gtk-theme#264]
There are plans to create a theme for Plymouth? With the ability to install the package `adapta-plymouth-theme`

**Comment by tista500** [comment]
Umm, to be honest, I dislike Plymouth. Because we've already got NVMe, PCIe SSDs (and/or RAIDs), if so, when we see that animation? In my machines, kernel space initrd takes 2 or 3sec, and user-space does 1 or 2sec, this case there's few chance to load animations within boot sequence...

And just my thoughts, that animation eats frame-buffer resources and improves nothing for usability.  For me, it's enough to be blank or show only boot warnings/errors. So I don't have any plans to do theming for Plymouth now.

Regards.

**Comment by igor-dyatlov** [comment]
Thanks for the answer. Closed

**Comment by dtrunk90** [comment]
I've colorized the ubuntu logo plymouth theme: https://github.com/dtrunk90/plymout-theme-ubuntu-logo-adapta
