### ISSUE TITLE
Spinner should be independet to vertical scaling

### ISSUE THREAD

**Issue by fb87** [adapta-project/adapta-gtk-theme#272]
Here I described my issue in Feedreader:
https://github.com/jangernert/FeedReader/issues/262#issuecomment-259233782

Is it possible, to set the correct spinner height respectless of the vertical scaling?

Btw.: As you see in the misscaled image, the borders on the up- and downside lose a lot of sharpness. Is there a way for a vectorized spinner?

**Comment by tista500** [comment]
The spinner in Adapta is independent from any other icon-themes, so Adapta has specific limitations about GtkSpinner (It means theming method is different from other themes).

> Btw.: As you see in the misscaled image, the borders on the up- and downside lose a lot of sharpness. Is there a way for a vectorized spinner?

This commit enhances the correct allocation for spinner: https://github.com/adapta-project/adapta-gtk-theme/commit/5eb5a736b3f9b49f0f3c198d03fe2ab7bac0a685, so it may be able to reduce blurring at the every 4 sides...

And then, as shown in your 2nd shot, that spinner seems completely meaningless, so that commit hides that spinner (for me, un-handleable).

Regards.
