### ISSUE TITLE
[Pragha] Buttons hard to see

### ISSUE THREAD

**Issue by HeikoAdams** [adapta-project/adapta-gtk-theme#276]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Xfce 4.12 
 ```

**Adapta version (if you knew)**
git master

**Related Application and/or Shell theming (or name of widget)**
Pragha 1.33

**Actual issue**
Pragha's buttons (play, pause etc) are hard to see because they are black on a black background

![bildschirmfoto_2016-11-11_20-35-59](https://cloud.githubusercontent.com/assets/1418818/20227820/7c9c0d1e-a84e-11e6-8d48-c7f82dd36b3d.png)

**Comment by tista500** [comment]
I don't know what that app is (because there is no installable package in Ubuntu main repository), see: https://github.com/pragha-music-player/pragha/blob/master/src/pragha-toolbar.c#L349

Those referenced icon names should be `xxx-symbolic`. So Adapta can NOT support such ancient applications (And this issue is NOT theme specific, means this will happen in other themes, too).

Closed.
