### ISSUE TITLE
Strange colors in some widgets of gno-menu using Adapta shell theme

### ISSUE THREAD

**Issue by ronisbr** [adapta-project/adapta-gtk-theme#291]
**Reporter info**

 ```
 * Distribution - openSUSE
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - GNOME 3.22
 ```

**Adapta version (if you knew)**
3.89.1.32

**Related Application and/or Shell theming (or name of widget)**
gno-menu (GNOME shell extension)

**Actual issue**
The colors of some widgets are strange in gno-menu when using Adapta theme. It is unreadable. This does not happen in -Nokto variants.

![gno-menu-adapta](https://cloud.githubusercontent.com/assets/1068295/20625009/792221b0-b2f7-11e6-9896-e610abcfef6e.png)

This is how gno-menu looks like in Adwaita:

![gno-menu-adwaita](https://cloud.githubusercontent.com/assets/1068295/20625046/cd1dd12e-b2f7-11e6-8da3-b273d268d7a1.png)

**Steps to reproduce (if you knew)**
Install gno-menu extension and change the theme to Adapta.

**Comment by tista500** [comment]
This is because Adapta does not support that extension.

Regards.

**Comment by tista500** [comment]
I won't support that extension because the design violates GNOME HIG. I suppose devs might want to port Slingshot and/or Cinnamon menu, but at least those are not needed in Gnome-Shell. Just use Pantheon or Cinnamon instead... Gnome-Shell already has the stock "Applications menu" extension which works fine, faster and stable.

Closed.
