### ISSUE TITLE
Theming application overview and search like in Zorin OS

### ISSUE THREAD

**Issue by fb87** [adapta-project/adapta-gtk-theme#294]
I just saw a screenshot of Zorin OS and thought, it (search box and result-highlighting) would also fit Adapta – what do you think?

http://news.tecmint.com/wp-content/uploads/2016/11/zorin-universal-search.png

**Comment by tista500** [comment]
Since this commit f551469, We've moved to Android 7.x design sources for Overview. So I don't have any plans to go back to zero-elevation (rest) search entry widget.

And once googling with the words "zorin OS desktop", we can see how they designed their desktops, as of their screenshots, their design philosophy seems almost *empty*. So we (at least I) will never learn the designs from them...

Regards.

**Comment by fb87** [comment]
Hi Tista. I didn't mean to adapt their design, I just thought it would be nice if the overview would be a little more colorful and darker. And the Zorin search box style looks a lot like regular dark Adapta text boxes – with the exception being the gray overview search box. :)
