### ISSUE TITLE
Gtk.CheckButton not themed correctly on Overlay

### ISSUE THREAD

**Issue by bil-elmoussaoui** [adapta-project/adapta-gtk-theme#330]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.2
 * Desktop environment -  Gnome
 ```

**Adapta version (if you knew)** Latest git version 

**Related Application and/or Shell theming (or name of widget)**
Any application that has a grid view with a selection option (this can be reproduced for example with Gnome Music). This only happens when the Gtk.CheckButton is used in Gtk.Overlay (like z-index on CSS but for Gtk widgets)

**Actual issue**
![adapta-bug-report-overlay](https://cloud.githubusercontent.com/assets/7660997/21956738/6b565724-da87-11e6-90b3-587651315897.png)

**Steps to reproduce (if you knew)**
Open Gnome Music, Select a grid view and enable selection mode. Click on any checkbox. The animation shows like an artifact behind it and it never disappears until you focus the parent of the Gtk.CheckButton which in this case is the album image (widget)

**Expected behavior**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> Any application that has a grid view with a selection option (this can be reproduced for example with Gnome Music).

That was true?
At least Gnome-photos 3.22.x does not have this issue.
I suspect this is related to: https://git.gnome.org/browse/gnome-music/commit/?h=gnome-3-22&id=f659a3327ee660fa92128f9f0cb83151c6416ff6

If so, devs violates standard GNOME-apps 'selection-mode' styling. It was enough we just only concern the `.view.content-view.check` style-class for selection-mode. But now Gnome-music does not seem to break this rule... :(

**Comment by bil-elmoussaoui** [comment]
Gnome Photos and other C/C++ applications modify those widgets you can see for example Gnome To-Do https://github.com/GNOME/gnome-todo/blob/master/src/views/gtd-list-selector-grid-item.c#L260 This only happens with Python applications. I can provide a video/example code on python if it will help you debug this easily :)

**Comment by tista500** [comment]
> Gnome Photos and other C/C++ applications modify those widgets you can see

Modify!?
No. Those are the standard widget design...

**Comment by bil-elmoussaoui** [comment]
Sorry i misexplained, i meant those widgets are drawn on a bigger scale (the size on Gnome-todo is 40px). Python cannot define the size of Gtk.CheckButton; that's why this issue is so visible on them.

**Comment by tista500** [comment]
> Python cannot define the size of Gtk.CheckButton; that's why this issue is so visible on them.

Hmm, I don't think so.
Because 'selection-mode' is the special mode of GtkView (or precisely GtkIconGridView?). Once 'selection-mode' ON signal was sent to GtkView, GtkView draws own checkbox onto `.view` style-class. When that happened, GtkView does not need to pull `check` and/or `checkbotton` node from the child object. So we usually do NOT set `check` node inside the styling of `selection-mode'. Please read my comment:
>  we just only concern the .view.content-view.check style-class

In 'selection-mode', GtkView adds special style-class `.check` for checkbutton styling, that's why we do not have to concern the `check` node for 'selection-mode' specific checkbutton styling.

But in Gnome-music, devs dropped GtkView container and added GtkFlowBox/GtkFlowBoxChild. So I said:
> But now Gnome-music seems to break this rule

Anyway this issue needs some enhancement for Adapta and all of Gtk+ theme if themes used animations in standard `check` node especially `:hover` and `:active` pseudo-classes.

**Comment by bil-elmoussaoui** [comment]
@tista500 Oh okey! thanks for the info; anyway, the Gtk.FlowBox is more flexible :) I've had this issue with an application I work and checked on Gnome Music if I can reproduce it ;)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/cdac332727dead2e03b5a157a7e48869c8c7f51c

Regards.

**Comment by bil-elmoussaoui** [comment]
Thanks for the fix, works just fine!
