### ISSUE TITLE
Make Adapta-Eta based on Flat-Plat Compact

### ISSUE THREAD

**Issue by mufeed20** [adapta-project/adapta-gtk-theme#342]
Simply what the title says.
From what I've seen, Eta always ends up being too small in size. I'm on a 1366x768 display, so I can tell which is the better spacing in smaller displays. And I've seen that Flat-Plat-compact is a Perfec Sizing while Eta ends up being too small.
Please, rebase Adapta-Eta to Flat-Plat-compact or improve spacing at the very least.
This is true for every version of Adapta-Eta.

**Comment by tista500** [comment]
>  rebase Adapta-Eta to Flat-Plat-compact

No.
Adapta is a different project from Flat-Plat. And your issue looks very subjectively. Adapta is the scaling Gtk+ theme based on the size of fonts. Most of widget sizes are calculated/scaled by font-size you've used.

If you did not like Adapta, please go back to Flat-Plat...

Regards.

**Comment by mufeed20** [comment]
oh sorry. Let me rephase all that.
I LOVE adapta. Adapta has been my default theme for a long time now. But Eta has too little spacing in the titlebar and such. After trying Flat-Plat-compact, I still stuck with Eta. I like Eta and don't feel like leaving it, ever BUT I need some way to fix the too-small titlebars (especially that).
I had said to rebase it because I thought that Adapta was still very similar to what it was once made from: Flat-Plat. After reading through the docs, checking out some code and such, I see that Adapta has evolved way beyond what Flat-Plat is.
Thank you

**Comment by tista500** [comment]
> I need some way to fix the too-small titlebars (especially that).

You've ignored issue-template already, so I could not reproduce any how...
For example, the height in Eta's SSDs are very similar to the Arc's one.
![ssds](https://cloud.githubusercontent.com/assets/6073622/22405488/ed219ae2-e686-11e6-929c-d7cd631ebf40.png)

Arc is 2px taller than our Eta (Font: 10.5pt Roboto Bold). On the other hand, standard Adapta is 6px taller than Arc. At least Eta should be smaller or equal to Arc, for me. Otherwise 'compact-mode' could not have its meanings.

Regards.

**Comment by mufeed20** [comment]
Is there any way to add more spacing in titlebar then?
