### ISSUE TITLE
Menubar broken on Thunderbird in Arch Linux

### ISSUE THREAD

**Issue by spheenik** [adapta-project/adapta-gtk-theme#358]
```
 * Distribution Arch Linux
 * Gtk+ 3.0 version: gtk3 3.22.8-1
 * Desktop environment Awesome
 ```

**Adapta version**

git HEAD

**Related Application and/or Shell theming (or name of widget)**

Thunderbird 45.7.1-2

**Actual issue**

Today's upgrade to Thunderbird, to version 45.7.1-2, has broken it's appearance when using the Adapta theme. The text on the menubar is gone, but I can still click into the void to open the corresponding menu. It seems like it's built against GTK3 now, so this might be the culprit.

The Firefox menubar works with the theme. Adapta was updated today after the problem appeared, which did not help, so it is current HEAD.

**Steps to reproduce (if you knew)**
Start said version of Thunderbird.

**Expected behaviour**
Being able to read the menu ^^

**Other Note (feature-request, question, etc...)**

[Bug report on Arch Linux Bugtracker, which contains a screenshot](https://bugs.archlinux.org/task/53051)

**Comment by spheenik** [comment]
Found some more breakage, with the message editor, I uploaded a screenshot to the Arch thread.

- The icons seem to be too dark
- The text is not there as well
- The "Over"-state of the buttons seems not styled at all

**Comment by tista500** [comment]
Hmm, 52.0-beta does not need any workarounds for GtkMenuBar:
![screenshot from 2017-02-23 20-02-22](https://cloud.githubusercontent.com/assets/6073622/23256601/78cb8ba4-fa03-11e6-827b-52e029a54957.png)

Personally, I won't add ugly workarounds for such *half-baked* Gtk+ 3.x integrations... :(

Regards.

**Comment by spheenik** [comment]
So you say the Thunderbird version the Arch guys use is too old and they integrated GTK3 in a way you'd describe as half-baked? 

I kind of expected that when I saw their 1000 line patch they applied named "firefix-gtk-320" or something.

**Comment by spheenik** [comment]
Can you recommend 52.0-beta for usage or does it really have the beta feel to it?

**Comment by tista500** [comment]
> So you say the Thunderbird version the Arch guys use is too old and they integrated GTK3 in a way you'd describe as half-baked?

In our Ubuntu 17.04 cycle, we still use Gtk+ 2.x versioned thunderbird 45.7.x. And I agreed their decision. Since FIrefox/Thunderbird improves GtkMenuBar/MenuItem integration in the 50.x to 52.x cycle (they fixed GtkCheckButton/RadioButton inside the GtkMenuItem and box-shadow property of GtkMenuItem in GtkMenuBar in 52.0.x cycle).

After releasing 52.0.x, we can purge some unneeded workarounds from CSSs added for Firefox at least. But still their Gtk+ 3.20/22 integration is ON the way, not finished yet for me.

> I kind of expected that when I saw their 1000 line patch they applied named "firefix-gtk-320" or something.

Many people expected Gtk+ 3.x integration, I know, but in most cases, they review those changes with Adwaita only. Still mozilla apps can not render "outset" box-shadow property of the GtkButton, but Adwaita can not notify that limitations to reviewers since Adwaita's raised buttons do not have such shadows but Adapta and Flat-Plat have. And Arc may seem OK because their buttons have very bold solid borders around the GtkButton without any shadows. But for us, bold borders are really ugly, in Material Design, raised material should be rendered with its shadow, elevation and thickness (z-axis). Even if we try installing Firefox 52.x, we will unfortunately see such mozilla's limitation in their widget composition especially in GtkButton...

> Can you recommend 52.0-beta for usage or does it really have the beta feel to it?

For me, 52.x series seem to run stable in both Firefox and Thunderbird in daily use.

**Comment by spheenik** [comment]
Thanks for the detailed explanation!
I guess I'll go with the beta then until the Arch guys upgrade :)
