### ISSUE TITLE
[Bug?] Problem with controls coloring on web elements

### ISSUE THREAD

**Issue by dein0s** [adapta-project/adapta-gtk-theme#378]
```
 * Distribution - PPA and build from sources
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Xfce4.12
 ```

**Adapta version (if you knew)** 
adapta-gtk-theme_3.89.5.43 from ppa

**Related Application and/or Shell theming (or name of widget)**
Firefox / Controls

**Actual issue**
Web dropdown controls are really (I mean **really**) hard to see. Other controls seems to be fine.
Just check this out (web dropdown on left side), normal window dropdown on right side
![](http://i.imgur.com/TvnQ7bY.png)
![](http://i.imgur.com/GjjouRm.png)
![](http://i.imgur.com/rsIXgLW.png)
And this happening to every default (not customized via js/css) selectors that I see.

I really like your theme, besides there're not so much MD-styled themes around. But this little thing just pissing me off.

Would be appreciated for any help with this. I'll provide any additional info if you need.

**Comment by tista500** [comment]
Hmm, this is very Firefox specific issue...

Because Firefox ignores dark-colour-variant if Gtk+ themes contained both light/dark variants. I'm not using Firefox to develop Web applications/sites though, please check how Chrome(ium) and/or Epiphany draws that combo-boxes.

Regards.

**Comment by dein0s** [comment]
In Chrome everything looks good.
From your previous comment I can assume, that if I install only dark-color-variant of - it may help with this issue, right?

**Comment by tista500** [comment]
Unfortunately maybe no... will make some side-effects.

Basically, those combo-boxes, buttons, and entries should follow the page's foreground colour scheme. Chrome(ium) overrides Gtk+ widget styling by using its own widgets, this is the normal behaviour of WebKit. But Firefox enforces embedding Gtk+ widget into pages with Gtk+ light colour shceme even if Gtk+ themes had both light/dark variants (so your popup context-menus are rendered with light variant colours even if you've selected dark-variant).

If we provided dark-variant only, this causes 'missing foregrounds' in wihite background pages with dark-variant foreground colours (very heavy side-effect). On the other hand, in Epiphany (WebKit2Gtk engine), it can render our specific 'fallback mode' widgets in pages, those widgets have solid coloured backgrounds behind the combo-boxes, buttons, and entries. Still entries can not be rendered with Gtk+ colour scheme (foregrounds of entries are rendered with pages' foregrounds) though, but at least it quite better than Firefox.

So I said this issue was very Firefox specific and solution is switching to other Gtk+ themes currently.

Regards.

**Comment by dein0s** [comment]
That's sad :|
Tough decision - switch from Firefox (which I got used with for dev/qa stuff) or find another dark-colored material design theme that will suit my esthetician needs :D

Anyway, thanks for the reply.
