### ISSUE TITLE
"No-notification" icon didn't change to the icon in Adapta shell theme

### ISSUE THREAD

**Issue by USBA** [adapta-project/adapta-gtk-theme#386]
**Reporter info**

 ```
 * Distribution - Fedora 26
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - GNOME 3.24 
 ```

**Adapta version (if you knew)**
Latest

**Related Application and/or Shell theming (or name of widget)**

message-list in the popup-menu (in GNOME shell theme) 

**Actual issue**
"No-notification" icon didn't change to the icon in Adapta gnome-shell theme.

**Steps to reproduce (if you knew)**

 

**Expected behaviour**

Change the no-notifications icon to your "no-notificaions" or "no-events" icon in the Adapta's gnome-shell theme directory. 

**Screenshot**
![screenshot from 2017-04-02 08-43-17](https://cloud.githubusercontent.com/assets/19838220/24584174/52cdd308-1754-11e7-98ef-f4058d38856f.png)

**Comment by tista500** [comment]
This is not the theme issue but upstream gnome-shell itself. Gnome-Shell pulls those icons from the `gresource` file placed in the path: `/usr/share/gnome-shell/gnome-shell-theme.gresource`.

So you need to override that gresource file manually to activate our svg icon set.

Regards.

**Comment by tista500** [comment]
Use our gresource installed in `/usr/share/themes/Adapta-*/gnome-shell/gnome-shell-theme.gresource`. Remember that you should select proper file exactly same with your selected gnome-shell-theme.

And most important thing is you should revert your changes for that gresource file whenever you'd like to switch to other themes, otherwise other theme's styling would be overridden by our specific gresource file, causes incorrect theming.
