### ISSUE TITLE
Window titlebars not changing colour

### ISSUE THREAD

**Issue by jim211083** [adapta-project/adapta-gtk-theme#389]
Distribution: Ubuntu Gnome 16.10
Gtk+ 3.0 version: 3.20.9
Desktop environment: 3.20.4

Adapta version: 3.90.0.40

Related Application and/or Shell theming (or name of widget): Theme

Actual issue:  When maximising windows the colour no longer changed to match in with the Gnome Shell bar at the top of the screen.  They stay the same grey colour as minimised windows.  This has only started happening in the last couple of days with recent updates of the theme.

**Comment by tista500** [comment]
Since the rev.29, I've dropped those maximization feature : https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.90.0.29

Because of some ancient Window-mangaers and non-native Gtk+ backends, I ended up, on the other hand, tiled effect was still alive though... So Mutter's server-side-decorations, GtkHeaderBar and GtkMenuBar keeps original background-colour when max'd, Sorry.

Regards.

**Comment by zgwerby** [comment]
Ok, then replace, plz on Gnome Shell Theme

#panel { height: 25px; background-color: /*#13191c*/ #2a373e; font-weight: 700; }

**Comment by tista500** [comment]
No, please use other themes.
