### ISSUE TITLE
Unreadable text tab tooltip on Google Chrome GTK+ 3

### ISSUE THREAD

**Issue by xpduyson** [adapta-project/adapta-gtk-theme#398]
**Reporter info**

 ```
 * Distribution - Debian Sid
 * Gtk+ 3.0 version - 3.22.12
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
3.90.0 Development Release (rev.89)

**Related Application and/or Shell theming (or name of widget)**
Google Chrome 59.0.3071.15 dev (GTK+ 3)

**Actual issue**
Unreadable text on tab tooltip (white text on white background)
![screenshot from 2017-04-22 08-53-17](https://cloud.githubusercontent.com/assets/6981890/25300456/0d72feb4-273a-11e7-9157-aacd2ee085ac.png)

**Expected behaviour**
It should be white text on dark background.

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/3b31dc52e57254733db53f66b88537ed7fc3265a

That's upstream issue because Chromium does not have the right way to get_style from `tooltip.background`, but it pulls `tooltip` node only. We do not set any background-color in that node itself but in `.background` style-class instead. So this issue is theme-unrelated...
