### ISSUE TITLE
Missing file when built/installed from source

### ISSUE THREAD

**Issue by skwerlman** [adapta-project/adapta-gtk-theme#416]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - i3wm
 ```

**Adapta version (if you knew)**
37c5aa3f (appears in earlier versions, too, but i didn't debug til now)
Built with `--parallel --enable-chrome`

**Related Application and/or Shell theming (or name of widget)**
Atom (but probably other electron apps too)

**Actual issue**
Menu bar and right-click menus in Atom are solid white. Running Atom without it's wrapper script reveals the following error:
```
(electron:22519): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1:78: Failed to import: The resource at “/org/adapta-project/gtk-3.22/gtk-contained-dark.css” does not exist
```

**Steps to reproduce (if you knew)**
Open Atom.
Re-run using `electron --app=/usr/lib/atom` to show the Gtk error.

**Expected behaviour**
Menu bars and right-click menus have readable text, highlighting, etc.

**Comment by skwerlman** [comment]
Investigating this further, it looks like the file is being generated, but not installed. I think I'v found the relevant bit in the makefile, and I'll submit a PR if I'm right.

**Comment by tista500** [comment]
This issue sounds quite strange. Because most of Gtk-backend (like Firefox, LibreOffice, Chromium, ...etc) works as we expected with our gresource files.

Currently I don't have any ideas why Electron Gtk+ 3 backend had such things. I'm sorry I won't do anything special for Electron Gtk+ 3 backend now.

Someday if Atom editor switches to current Chromium-like backend, I will re-open and re-track this. Closed...

Regards.

**Comment by tista500** [comment]
This was the packaging issue: #442.
I've already mentioned that GNU Parallel should not be used when packaging in README.md, but some distro contributors still use that option... :(

Should be fixed that commit.
