### ISSUE TITLE
Color variants

### ISSUE THREAD

**Issue by Madis0** [adapta-project/adapta-gtk-theme#435]
Hello, 
I really like the look of Adapta with it's Material-looking design elements and animations. 

However, Material Design does focus a lot on color, so I was thinking - what if you made a normal and Eta theme to add colored titlebars to programs? The implementation could be similar to [Paper theme](https://github.com/snwh/paper-gtk-theme): [(screenshots from webupd8.org)](http://www.webupd8.org/2014/12/paper-new-material-design-inspired-gtk.html)

![Screenshot 1](https://3.bp.blogspot.com/-PzQQB3x6VuI/VJLHJ2sdD6I/AAAAAAAAVGs/qqTqQdeF0HA/s1600/paper-gtk-theme.png)

![Screenshot 2](https://2.bp.blogspot.com/-4IL8597IZR8/VJLHCI1yn_I/AAAAAAAAVGk/e48Wu0ADIeM/s1600/paper-gtk-theme-of.png)

**Comment by tista500** [comment]
Hmm, I've already answered to some closed reports, those feature of that theme will be no longer available in Gtk+ 3.2x or higher. This is because we've completely moved to node-name/id and style-class theming. Although some fine-tuned Gtk+ apps have specific node-name of its GtkWindow, but there's no plan to implement those features currently...

So I set this question as "won't fix", sorry.

Regards.
