### ISSUE TITLE
Error in .rc files

### ISSUE THREAD

**Issue by SandPox** [adapta-project/adapta-gtk-theme#445]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**
3.91.0.140-0ubuntu1~zesty1

**Related Application and/or Shell theming (or name of widget)**
VMware Workstation 12

**Actual issue**
These error printed out when run "vmware" in Terminal:
 ```
/usr/share/themes/Adapta-Eta/gtk-2.0/common-eta.rc:1269: error: unexpected identifier `direction', expected character `}'
/usr/share/themes/Adapta-Eta/gtk-2.0/3rd-party-eta.rc:430: error: invalid string constant "standalone_entry", expected valid string constant
 ```

**Steps to reproduce (if you knew)**
~$ vmware

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
Is this a problem or it's ignore-able? because VMware UI did looks like having some kind of error while applying theme.

Ambiance theme:
![image](https://user-images.githubusercontent.com/14113155/27722369-c2aff884-5d56-11e7-86ad-f49bb3a496ad.png)

Adapta-Eta:
![image](https://user-images.githubusercontent.com/14113155/27722357-b06e765a-5d56-11e7-9ca9-3dd11effdd5a.png)

As you see, on Adapta theme, the tabs and indicator on bottom-right have some strange looking border (like Windows basic theme) while on Ambiance have more proper looking UI.

**Comment by tista500** [comment]
> `/usr/share/themes/Adapta-Eta/gtk-2.0/common-eta.rc:1269: error: unexpected identifier `direction', expected character `}'`

> Ambiance have more proper looking UI.

This is ignore-able. Because their Gtk+ 2 backend may or may not have some incompatibility with our standard "pixmap" engine. Those should never happen in native Gtk+ 2 apps. Check Adwaita as well.
Ambiance is based on "Murrine" engine. Although we have a piece of theming with Murrine-dependency, but ours is just for GtkLabel only. 

VMWare is too problematic in various Gtk+ 2 themes now and then. So I don't want to do anything for it. 

> `/usr/share/themes/Adapta-Eta/gtk-2.0/3rd-party-eta.rc:430: error: invalid string constant "standalone_entry", expected valid string constant`

Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/77e028c53545901c3c11747229ad0db723aad313


Anyway I won't add VMWare specific fix, sorry.

Regards.
