### ISSUE TITLE
RFE: Slick Greeter?

### ISSUE THREAD

**Issue by ikeydoherty** [adapta-project/adapta-gtk-theme#459]
Very simple Q: Any interest in supporting [slick-greeter](https://github.com/linuxmint/slick-greeter) ?

**Comment by tista500** [comment]
I didn't know that greeter...

**Comment by tristan957** [comment]
@tista500 it's a fork of Ubuntu's LightDM Unity Greeter being developed by Linux Mint. It is currently the default in Linux Mint and I think Solus unstable.

**Comment by ikeydoherty** [comment]
It's totally cool if you're not up for it, I understand :)

**Comment by tista500** [comment]
@tristan957,

> it's a fork of Ubuntu's LightDM Unity Greeter being developed by Linux Mint. 

Oh I'm really afraid of the combo of terms "LinuxMint and Unity"...
Basically Unity7 resources strongly depend on floods of pixmap images, no CSS, no plain text theme files. For me, that's truly painful thing, means most of things are out of control.

And LinuxMint devs frequently use Python-gtk bindings to create the GUIs. Then that happens, in most cases, our debugging tool "CSS inspector" does not work for such Python-ed apps. If so, everytime I need to track their sources to estimate the style-classes, selectors, node names...
Totally painful and wasting my developing time. :(

Regards.

**Comment by tristan957** [comment]
@tista500 I haven't looked much into how it is themed. I know @ikeydoherty has poked around a bit. Their github repo is 96% Vala though so that should cross your Python worry off the list! This greeter has no connection to Unity other than it being used to launch Unity. I remember from my Ubuntu days that the greeter easily changed themes. I don't know how much Arc supported it, but I do remember the greeter menus being Arc themed when I had that theme enabled. Hope this eases your worries a bit!

**Comment by tristan957** [comment]
Searching through their github repo I have found 23 [references](https://github.com/linuxmint/slick-greeter/search?p=1&q=style&type=&utf8=%E2%9C%93) to the word style, but some of those are in svgs. Not entirely sure how GTK+ theming works but I do know `add_class` has something to do with it. There seem to be 5 style [classes](https://github.com/linuxmint/slick-greeter/search?utf8=%E2%9C%93&q=add_class&type=) referenced within the greeter. Hope you find this helpful

**Comment by tista500** [comment]
Yeah I knew things: http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/view/head:/Ambiance/gtk-3.20/apps/unity-greeter.css

But worst thing is I have to revive the unity-greeter styling that I've already purged completely. Everybody knows Unity7 resources are almost outdated. :(

Anyway I will see how it works in this weekend (Because of my rough tests, that greeter crashes with 'lightdm --test-mode' and ignores my 'setxkbmap' autostart script of my X11 sessions. So I need more time to prepare for the test environments).

Regards.

**Comment by tista500** [comment]
Ugly commit: https://github.com/adapta-project/adapta-gtk-theme/commit/efcf9c9fe31f62dd7bdbad7bdf0a7b4b8f379cb8

For me, that greeter was too poor to support, so please do not expect too much, almost everything is  broken in design...

Regards.

**Comment by ikeydoherty** [comment]
Cheers @tista500  - much appreciated. Sorry for putting that Unity stank on your codebase :]

**Comment by tista500** [comment]
@ikeydoherty,
@tristan957,

I think most of `data/*.png` and `data/*.svg` can be replaced with CSSs and icon-themes instead, so I hope someday upstream could drop those image files... ;)

Regards.

**Comment by tristan957** [comment]
Thanks for the communication and updates @tista500
