### ISSUE TITLE
[Featured Request] Adapta Grub theme for GNOME?

### ISSUE THREAD

**Issue by Warmuser** [adapta-project/adapta-gtk-theme#464]
Dear developer, are you planning to create a Grub theme for adapta-gtk-theme soon? Expecially for Arch/Manjaro. Thanks

**Comment by tista500** [comment]
I can't get the point of your request... Plymouth?

And we will not add any distro-specific external theming.

Regards.

**Comment by tristan957** [comment]
@Warmuser are you referring to a GDM theme? I would suggest Flat-Plat for a good GDM theme

**Comment by tista500** [comment]
A closed report about Plymouth: #264.

> I would suggest Flat-Plat for a good GDM theme

o_O? We already have though...

**Comment by tristan957** [comment]
@tista500 whoops I didn't know. I must be blind. Gonna have to go check the readme again

**Comment by tista500** [comment]
@tristan957,

We do not mention our gdm-greeter styling in README.md because overriding gdm-greeter is breaking other gome-shell themes even if Adapta gdm-greeter was applied to the Adapta-Nokto gnome-shell theme. So that's our hidden feature for those who know what they're doing with `gnome-shell-theme.gresource`. : https://github.com/nana-4/Flat-Plat#gdm-locklogin-screen

**Comment by tristan957** [comment]
@tista500 thanks for the information. Cheers!

**Comment by tista500** [comment]
Currently there's no plan to implement grub2 graphical theme nor plymouth theme, sorry.

Closed.

**Comment by Warmuser** [comment]
@tista500 May Sorry, maybe I'm late, but also the logout and notification popups are into the gdm-greeter? Because I want to ask you If you will customize them In the future. Thanks :)
