### ISSUE TITLE
[Enhancement request] Can you change the GNOME dialogs like the white popup menus?

### ISSUE THREAD

**Issue by Warmuser** [adapta-project/adapta-gtk-theme#472]
Hello (again lol), this time I want to ask you If you are planning to customize the default GNOME dialog popus and notification popus in like these theme: http://imgbox.com/o57MSiiL

Things to customize: 

http://imgbox.com/sm5spypR
http://imgbox.com/HgUBeAfs
http://imgbox.com/NnERZYqq

I'm sorry to open again the request, but the latest post has been closed much faster. :)

**Comment by tista500** [comment]
> I'm sorry to open again the request, but the latest post has been closed much faster. :)

The previous reprt had a title: [Featured Request] Adapta Grub theme for GNOME?
I don't think that report and this are related.
So what do you want me to do?

**Comment by tista500** [comment]
> this time I want to ask you If you are planning to customize the default GNOME dialog popus and notification popus in like these theme

No, I won't .
Because we have different design source between Popover and OnScreenDisplay.
White on White OSDs are sometimes lacking focus and readability even if modal-effects are applied. Gnome-Shell renders most of modal-dialogs as 'modal' though. So we use inverted notification banners, modal-dialogs, tooltips, and message-dialogs in light-variants.

On original MD, they had some samples light dialogs on light-variants because they can render all of dialogs as "perfect modal dialogs", but on the other hand, we can't do outside the Gnome-Shell. I don't think Gnome-Shell theming having some special light dialogs is not semantically right.

So we have inverted OSDs in GS, Cinnamon, Budgie, Mate, LXDE, XFce and most of supported desktop environments. Won't fix, sorry.

Regards.
