### ISSUE TITLE
[Gnome-Control-Center] Printer Details windowbar doesn't render correctly

### ISSUE THREAD

**Issue by chrisweeksnz** [adapta-project/adapta-gtk-theme#502]
**Reporter info**

 ```
 * Distribution - Solus 3
 * Gtk+ 3.0 version - libgtk-3, version: 3.22.18, release: 62
 * Desktop environment - Budgie
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

adapta-gtk-theme, version: 3.91.2.129, release: 100

**Related Application and/or Shell theming (or name of widget)**

Gnome Control Center - Printers - Printer Details Dialogue Box

**Actual issue**

When opening 'Printer Details' on a printer, the windowbar is rendered only 1-2 pixels wide and therefore you cannot see the close window widget. The only method of closing the window was shortcut key (alt-f4) or changing theme and then clicking the widget.

**Steps to reproduce (if you knew)**

Menu -> Settings (to launch gnome control center)
Select Printers
On a printer that is configured, click the 'Cog' icon and select 'Printer Details'
At this stage, the Dialogue box will open, but the window bar will be very thin. This doesn't happen on the other options from the 'Cog' icon, eg. 'Printing Options'

Example of the broken windowbar rendering:
![adapta-bug_printer-details_the-problem](https://user-images.githubusercontent.com/11150429/30086631-364e097e-92f0-11e7-87c2-db576d553a6b.png)

**Expected behaviour**

The dialogue box opens with a windowbar with the normal width and renders the close window widget.

Example of correctly rendered windowbar in the arc theme:
![adapta-bug_printer-details_rendered-on-arc-theme-properly](https://user-images.githubusercontent.com/11150429/30086630-364d5600-92f0-11e7-8878-5c82b9cf7261.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Upstream report: https://bugzilla.gnome.org/show_bug.cgi?id=784562

For me, it's upstream issue in their Python codes and/or ui file.
In general, the height of GtkHeaderBar should be computed (allocated) by its own child widget allocations like GtkButton, GtkLanel, GtkBox etc... I also think there's no reason to set `min-height` property in GtkHeaderBar, at least in Adapta. That's the different appearance between Adapta and Arc (Arc may set `min-height` to GtkHeaderBar styling).

So that dialog Gtk+ said a warning:
```
Gtk-WARNING **: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
```

This means their approach to construct GtkDialog seems to ignore the child allocation completely, so I don't think this is theme-side issue. GtkHeaderBar should be allocated without `min-height` property (like other standard GtkDialogs have).

Regards.

**Comment by tista500** [comment]
> GtkHeaderBar should be allocated without min-height property (like other standard GtkDialogs have).

I meant "if GtHeaderBar has one or more child widgets, the height of GtkHeaderBar should be determined by the height of its own child widgets, even if GtkHeaderBar's `min-height` was set as `0`. Because that was NOT `height` but `min-height`."

Regards.

**Comment by tristan957** [comment]
I too noticed this in the past. Thanks for the new info @tista500

**Comment by tista500** [comment]
Currently there's no plan to set `min-height` to GtkHeaderBar, so I close this unfortunately, sorry.

Regards.

**Comment by tista500** [comment]
Ugly commit: https://github.com/adapta-project/adapta-gtk-theme/commit/b88d553f00835206b0f5f9b9091ce4fd688a91c0

Kill Python, please...

**Comment by tista500** [comment]
I'm sorry I was wrong. PpDitailsDialog is here: https://git.gnome.org/browse/gnome-control-center/tree/panels/printers/pp-details-dialog.c
PpOptionDialog was no problem...

**Comment by tista500** [comment]
Release: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.92.1.33
