### ISSUE TITLE
Adapta & Adapta-Nokto font issue on Budgie Desktop

### ISSUE THREAD

**Issue by pommetjehorlepiep** [adapta-project/adapta-gtk-theme#540]
**Reporter info**

 ```
 * Distribution - Solus 3 (3.26.1)
 * Gtk+ 3.0 version - 3.22.24
 * Desktop environment - Budgie 10.4
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
3.91.2.241

**Related Application and/or Shell theming (or name of widget)**
Adapta + Adapta-Nokto
Veracrypt 1.21

**Actual issue**
Veracrypt: Text on some buttons not fully displayed.

**Steps to reproduce (if you knew)**
Just run Veracrypt and you see it.

**Expected behaviour**
Text fully visible on buttons.

**Other Note (feature-request, question, etc...)**
Text is properly displayed when using **Adapta-Eta** or **Adapta-Nokto-Eta**

![veracrypt font issue](https://user-images.githubusercontent.com/8982487/31926812-4bd42b02-b8d4-11e7-986a-a743a62d04ca.png)

**Comment by tista500** [comment]
What the fxxk!?

Related to this code?: https://github.com/veracrypt/VeraCrypt/blob/master/src/Main/Forms/MainFrame.cpp#L336

I'm not quite sure about building UIs via wxGTK, but for me, they just compute those button height from scaling GtkLabel height only? If so, we can't support that app at all.

> Text is properly displayed when using Adapta-Eta or Adapta-Nokto-Eta

Because Eta variants have 2px `inner-border' style property and 4px `x/ythickness' (on the other hand, Adwaita has 4px inner-border + 2px x/ythickness). Then that app seems to ignore `inner-border` property. And the height of GtkEntry seemed to be mis-allocated as well even in Eta variants and Adwaita themes, right?

Personally I don't want to do anything for that app. Becayse reducing x/ythickness will introduce heavy side-effect in Qt-Gtk backends. I don't think stem of this issue was related to theme-side.

So I set this "Won't fix", sorry.

**Comment by pommetjehorlepiep** [comment]
No problem @tista500  I completely understand. I'll raise an issue with Veracrypt. Thx
