### ISSUE TITLE
Nautilus uses dark text on dark background for menus

### ISSUE THREAD

**Issue by viggy96** [adapta-project/adapta-gtk-theme#548]
**Reporter info**

 ```
 * Distribution - Ubuntu
 * Gtk+ 3.0 version - 3.22.24-0ubuntu1
 * Desktop environment - GNOME
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.92.1.9-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**
Nautilus 3.26.0

**Actual issue**
Menus in Nautilus uses dark text on dark background making the options impossible to read.

![image](https://user-images.githubusercontent.com/9837626/32524708-05066584-c3ef-11e7-8431-2c2c82a27f60.png)

**Comment by tista500** [comment]
> * Distribution - Ubuntu
> * Gtk+ 3.0 version - 

version?

**Comment by tista500** [comment]
I could not reproduce at least on Bionic nor Artful with Nautilus 3.26.x...

**Comment by viggy96** [comment]
GTK version is: 3.22.24-0ubuntu1

**Comment by tista500** [comment]
I don't think this is a theme specific issue, then there's few things I have to track down... Try logout & login or kill and restart Nautilus if no active/pending tasks.

And use our proper package for Artful instead of Xenial. The contents of those packages and build environments are not the same.

I'm sorry I can't help this report.
