### ISSUE TITLE
Adjusting text position in notifications

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#549]
**Reporter info**

 ```
 * Distribution - Fedora 27b
 * Gtk+ 3.0 version - 3.22.24
 * Desktop environment - Gnome 3.26.1
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.91.2-2.20171008

**Related Application and/or Shell theming (or name of widget)**
Gnome notification center.

**Actual issue**
First: You new frame style is REALLY nice! Thanks very much!
The Bug: Like you see in my attached screen shot, the left edge of the first notification is displaced and should align with the second one. Maybe an issue due to my UHD screen.

![bildschirmfoto von 2017-11-09 02-26-35](https://user-images.githubusercontent.com/10520767/32583890-f8c41c1e-c4f5-11e7-82a2-a822ff334c02.png)

**Steps to reproduce (if you knew)**
Using Adapta on a UHD screen…?

**Expected behaviour**
Texts of both notification aligned.

**Comment by tista500** [comment]
Bug!? How could you determine this issue was a bug of us? I haven't tracked down the Gnome-Shell codes yet...

Then without a left-most StIcon of the NotificationBanner, all of child StBoxLayout of Notification content should be automatically aligned to most-left with its interanal padding and/or outer margin.

**Comment by fbruetting** [comment]
Sorry! I hadn’t even recognized, that this behaviour is the same with Adwaita, my bad!
