### ISSUE TITLE
Cannot connect to openconnect due to missing buttons

### ISSUE THREAD

**Issue by baimafeima** [adapta-project/adapta-gtk-theme#550]
This was first reported downstream here: https://dev.solus-project.com/T4596
I cannot connect to openconnect because the buttons to add a VPN network are missing at the bottom of the openconnect configuation window (see screenshot in downstream link)

 ```
 * Distribution - Solus 3
 * Desktop environment - Budgie
 * Display server protocol - X11
 ```

**Comment by tista500** [comment]
o_O?

![screenshot from 2017-11-11 08-43-41](https://user-images.githubusercontent.com/6073622/32683260-63c22768-c6bd-11e7-8823-f1f7de321d4f.png)

Gnome-Control-Center 3.26.1
Network-manager-openconnect-gnome 1.24.1
Roboto Regular 10.5pt
Font-scaling-factor 1.0

Results that GtiDialog height 792px with Adapta, 712px with Adapta-Eta. So what is the problem??

**Comment by tista500** [comment]
And let me see how Adwaita works on Original Reporter's machine(s).

**Comment by tista500** [comment]
![screenshot from 2017-11-11 09-21-33](https://user-images.githubusercontent.com/6073622/32683875-13492534-c6c2-11e7-8f03-6eb7fb9a036a.png)

Gnome-Control-Center 3.24.1
Network-manager-openconnect-gnome 1.2.4-1
Roboto Regular 10.5pt
Font-scaling-factor 1.0

Screen Resolution 1366x768
Theme Adawaita-Dark

**Comment by tista500** [comment]
This? : https://bugzilla.gnome.org/show_bug.cgi?id=712417

**Comment by tista500** [comment]
OR seems to open that GtkDialog via:
```
nm-connection-editor -> Add connection -> xxxxx (openconnect) in the VPN category -> Select
```

https://git.gnome.org/browse/network-manager-openconnect/tree/properties/nm-openconnect-dialog.ui

**Comment by baimafeima** [comment]
@tista500 My screen resolution is 1366 x 768. Why no fix for this?

**Comment by tista500** [comment]
Because this will potentially happen in all of user-themes in some combinations screen resolutions and font-size * font-scaling. Actually Adwaita does as well. So this should be fixed in upstream network-manager-openconnect.

Then that GtkDialog has too many rows in a single GtkNotebook's GtkStack. If so, GtkStack should contain the GtkScrolledWindow and set porper preferred_height for initial height of GtkDialog.

And finally that GtkDialog does not have any specific style-classes/node-names for styling. We can't add any special styling, I meant.
