### ISSUE TITLE
Change Activities Overview for an Icon

### ISSUE THREAD

**Issue by snydox** [adapta-project/adapta-gtk-theme#619]
Have you considered changing the Activities Text string for an Icon?

Through the activities-configurator extention I placed a little icon with vertical lines. IMHO it looks better than the text "Activities."

![img-20180112-wa0014](https://user-images.githubusercontent.com/13590875/35216621-0f6b1f2e-ff1d-11e7-9a63-6ae4c770ca16.jpg)

**Comment by tista500** [comment]
> Have you considered changing the Activities Text string for an Icon?

No. Because the right place to discuss for the design of that PanelButton might be Gnome Bugzilla. If upstream was going to replace that StLabel with StIcon, we'll follow their changes though...

> Through the activities-configurator extention I placed a little icon with vertical lines. IMHO it looks better than the text "Activities."

The advantage of replacing with StIcon is saving the horizontal space inside the TopBar. So StIcon might be suitable on some poor resolution LCDs like WXGA and/or 1080p though it depended on the  numbers of PanelButtons and extensions are placed in TopBar...

And once we'd employed such asset images with 'hard-coded' in user-themes, some conflicts may or may not happen with those extensions you installed to override the appearance of 'Activities' PanelButton.

So currently there's no plan overriding 'Activities' PanelButton anyway, then use those extensions instead, please.

**Comment by tista500** [comment]
I set this "Won't fix", sorry. In future, we may or may not change this with regardless though...

**Comment by snydox** [comment]
I see. Thanks for the feedback. I really love the Adapta GTK theme. Keep up the good work!
