### ISSUE TITLE
Question - GTK3.18 EOS

### ISSUE THREAD

**Issue by smurphos** [adapta-project/adapta-gtk-theme#666]
Hi Tista,

Am I correct in thinking that once GTK3.18 EOS is reached at the end of the month that the PPAs will offer updates breaking the GTK3.18 theme?

If so do you have any objection to a GTK3.18 supported build being hosted at https://cinnamon-spices.linuxmint.com/. This would be primarily aimed at Mint 18 users. Mint 19 with GTK 3.20+ isn't due for release until mid summer and many Mint users stick with the previous LTS for extended periods in any case.

I'd ensure that the license was included and include credits / links to source.

Thank-you.

**Comment by tista500** [comment]
> Am I correct in thinking that once GTK3.18 EOS is reached at the end of the month that the PPAs will offer updates breaking the GTK3.18 theme?

No. I will *delete* all of xenial-related PPA packages in 26th Apr, then `apt update` will notify you some errors caused by missing target release. It means your installed PPA packages won't be updated anymore ( = EOS).

 > If so do you have any objection to a GTK3.18 supported build being hosted at https://cinnamon-spices.linuxmint.com/. 

I will also do these things:
* Purge the Gtk+ 3.18.x related sources from git.
* Rewrite some SCSSs to be more matched with 3.2x/4.0 (i.e: change some colour variable names).
* Rewrite autoconf/automake sources to stop accepting for `--enable-gtk-legacy` option.

**Comment by tista500** [comment]
Anyway I'm OK. I no longer maintain the Gtk+ 3.18.x sources though...

**Comment by smurphos** [comment]
Thank-you.
