### ISSUE TITLE
Adapta theme for Firefox?

### ISSUE THREAD

**Issue by user501254** [adapta-project/adapta-gtk-theme#69]
There's some mismatch of color (between title bar & tab bar) as well as style when using Firefox under the theme.
A Firefox specific theme would be great.

**Comment by stelariusinfinitek** [comment]
Just a suggestion : use [this Firefox theme](https://github.com/horst3180/arc-firefox-theme/releases).

**Comment by jmcs** [comment]
I forked arc-firefox-theme dark to make it more consistent with Adapta: https://github.com/jmcs/arc-firefox-theme

Keep in mind that this is still very much a work in progress.

**Comment by vltr** [comment]
wow, nice job @jmcs ! I think that with a little polishment here and there, it'll look fantastic.

![selection_008](https://cloud.githubusercontent.com/assets/1540275/18586058/04e60f60-7bf1-11e6-9c30-9af65068c159.png)

**Comment by vltr** [comment]
I have some Qt related stuff in my computer to match Adapta (either using `qt5ct` or others). It's incomplete but it's a start.

@tista500, just a thought: elevating Adapta as a group / project, it would be easier to find Adapta related stuff and have others contributing to anything they want in Adapta as sub-projects, since a KDE theme to Steam or who knows what else ... Well, it's just an idea :wink:

**Comment by tista500** [comment]
Sorry for my super delayed response...

@vltr,

> elevating Adapta as a group / project, it would be easier to find Adapta related stuff and have others contributing to anything they want in Adapta as sub-projects

Sounds cool. ;)
So I'm now thinking to make organization and transferring `tista500/Adapta` to `adapta-project/adapta-gtk-theme` or something like that... So what will be the name of organization, `adapta-project` is fairly enough?

I also imagine we need to hunt the Logo of Adapta-Project as well...

@jmcs,

Thanks for your implementation! :)
Seems nice and I could not do like that because I do not have much skills to make firefox theming...

Regards.

**Comment by vltr** [comment]
yey! thanks @tista500 , for listen to us! :smile: 

the idea of creating `adapta-project` is awesome, but i don't know if you should create it without a specific goal - i mean, numix have all their themes and icons and even a distro / custom mutter. the thing i want most in my linux desktop (which have been my default desktop for a decade now) is that everything can look the same, either you're using gnome-shell (in my case), or cinnamon, unity, kde, you name it. it is hard to jump between applications and  have your "visual harmony" broken. the guys of elementary made an excellent job, but at the cost of thousands of man / hour work - which i think it's something not everyone has.

when i bumped into adapta, which uses the material concept (that i was already aware of), it was easy to start customizing other tools and apps, like qt creator (one of the tools i use), sublime text (that already has a material theme), terminator colors, qt5ct, qss and forward ... @jmcs made an excellent spin from arc-firefox-theme to get a firefox theme closer to adapta. i do not think it would be impossible to help users, based on the adapta theme, to get an uniform look between apps :smiley: 

i'm no gnome expert to create those wonderful themes (i'm not that creative, too) - but i do like to customize :wink: here's a screenshot of my desktop:

![screenshot from 2016-09-30 08-48-55](https://cloud.githubusercontent.com/assets/1540275/18990845/3040931a-86eb-11e6-85da-1c3639314ace.png)


for me that would be a project i could work, even on documentation (i kind of live for that lol). wikis are great ...

**Comment by tista500** [comment]
Greetings,

I've created `adapta-project` organization: https://github.com/adapta-project
It's still almost empty, then I will transfer my repository there in **Fri, 14 Oct 2016** maybe... ;)

Regards.

**Comment by tista500** [comment]
@vltr and @jmcs,

I've sent invitation to you guys, so if you could, join the project and create/transfer your branch... ;)

Regards.

**Comment by vltr** [comment]
Oh yeah! I'll probably start with documents or wiki! Thanks a lot, @tista500 :)

**Comment by dralley** [comment]
@vltr Unrelated question to this issue, but what did you use for that dock?  Is that just Dash to Dock with some tweaks?

**Comment by vltr** [comment]
@dralley yeap, Dash to Dock with some tweaks :smile: 

Well, I don't remember now what I have done exactly, but sure thing I can strip it down later if you're interested :+1:

**Comment by vltr** [comment]
@dralley , hope this helps:

![screenshot from 2017-02-02 11-38-06](https://cloud.githubusercontent.com/assets/1540275/22551682/e338c6fa-e93c-11e6-960d-d386f5f3b2f8.png)

![screenshot from 2017-02-02 11-40-25](https://cloud.githubusercontent.com/assets/1540275/22551688/e8725d7a-e93c-11e6-85f9-6e0c59a201ee.png)

Color hex code: ```#455A64```

:wink:

**Comment by pablocuesta92** [comment]
I modified a Stylish theme by @Scindix and @nana-4 to match the adapta color palette: https://github.com/pablocuesta92/adapta-firefox-theme


![](https://camo.githubusercontent.com/f98ce62d44dcc1a2043f57710ee307262b13612f/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f6e70646c30703864316673743266382f6164617074612d66697265666f782d7468656d652e706e67)

**Comment by vltr** [comment]
Hey, @pablocuesta92, nice one 👍 !! I did like the combo! It still lacks some polishment (as you can see on my screenshot below), but it really looks promising! Do you think you can make it as a XPI file, instead of installing stylish? It would be great to have the base theme in a XPI file and tweak / customization options based on stylish 😉 You can get inspired by an [arc firefox theme fork previously mentioned in this same issue](https://github.com/jmcs/arc-firefox-theme) by @jmcs ...

@tista500 : what do you think about bringing this home?

@pablocuesta92, this is how it looks in my box, using Adapta Nokto Eta:
![screenshot from 2017-02-16 08-53-18](https://cloud.githubusercontent.com/assets/1540275/23018970/5f22d6ee-f427-11e6-804f-2715fa04568b.png)

**Comment by mufeed20** [comment]
um... but isn't firefox's theming support gonna die soon?

**Comment by vltr** [comment]
@mufeed20 so much for desktop customization, sigh ... Anyway, is there a deadline for this to happen?

**Comment by mufeed20** [comment]
@vltr 'Complete Themes' is whats dying. And that's what the Arc theme used to be. The deadline set is Firefox 57, around November this year.  
But seeing how Photon (the new firefox UI design) is just like Adapta, I don't really think we'll be needing a theme anymore. Just a matter of a color scheme.   
[Reference Link](https://www.bleepingcomputer.com/news/software/mozillas-plans-for-firefox-themes-in-2017/)

**Comment by vltr** [comment]
Thanks, @mufeed20 ! I'm not following Firefox development on a daily basis, but that's interesting news. Let's see how Photon will behave under Linux then ... :wink:

**Comment by TechnoTrancer** [comment]
Hi, i'm currently using this Firefox theme https://addons.mozilla.org/en-US/firefox/addon/nokto-lightweight/ 

![image](https://user-images.githubusercontent.com/10563069/26907406-2ffb5ea6-4bb9-11e7-9431-e066b92c4cc0.png)

It's perfect for me

**Comment by makmm** [comment]
Offtopic, @vltr What is that font? It looks very nice :)

**Comment by vltr** [comment]
@makmm it's "[Ciutadella Rounded](http://emtype.net/fonts/ciutadella-rounded)" ... it's not a free font, unfortunately. sorry for let you down on that :pensive:

**Comment by makmm** [comment]
@vltr Okay, what did you end up using to make it match with adapta?

**Comment by vltr** [comment]
@makmm well, I don't quite understood your question - but may I say I do have dyslexia, so I searched a lot for font faces that matches or pleases me better - for me it's a big deal. I'm using this font face with Gnome for more than a year now (since I found it, actually). As for applying / configuring, I just use ```gnome-tweak-tool``` (or ```gsettings``` in the command line) and have a little script that changes the font-family from the current gnome-shell CSS theme, in this case "Adapta-Nokto" :wink:

**Comment by makmm** [comment]
@vltr Oh okay.
But what I mean't is what did you end up putting on firefox to make it match with adapta?

**Comment by vltr** [comment]
Oh! My bad! I told you I didn't understood, lol. Ok, I just tested the
theme mentioned in this issue (at the time), but now I just use the new
dark theme embed with Firefox, and it looks awesome ;-)


Em 20 de jun de 2017 7:50 PM, "makmm" <notifications@github.com> escreveu:

**Comment by makmm** [comment]
@vltr OHH Thanks!! That looks really.. Okay. Thanks a lot.

**Comment by vltr** [comment]
@makmm well, here's my Firefox and what it looks like with Adapta. The colors don't quite match (yet?), but I think that's something easy to overcome in the future:

![screenshot from 2017-06-21 11-04-28](https://user-images.githubusercontent.com/1540275/27388427-d244dbac-5671-11e7-8aa7-00cfc9851339.png)

And the current Firefox version for reference (on my Arch Linux):

![screenshot from 2017-06-21 11-05-01](https://user-images.githubusercontent.com/1540275/27388442-e0a1b6f2-5671-11e7-97db-d210b960ce59.png)

PS: I'm really sorry I didn't got your question and made a messy explanation leading to nowhere :sweat_smile:

**Comment by vltr** [comment]
Just to get back on track about Firefox theming, I think this should be put on hold (at least for now) until Firefox 57 arrives, as mentioned [here](https://github.com/adapta-project/adapta-gtk-theme/issues/69#issuecomment-297252035). As for today, Firefox nightly is still on version 56.0a1, which means we are not certain what will follow (yet). When 57 arrives (and newer Firefox versions), we can then see what will happen with Photon, if it'll blend nice with your desktop environment (or not), what can be done regarding customization (color schemes?), that sort of stuff ...

![screenshot from 2017-06-21 16-05-37](https://user-images.githubusercontent.com/1540275/27402004-960abccc-569b-11e7-9370-73749db97267.png)

**Comment by Armanmd** [comment]
@vltr whats your zsh theme ?

**Comment by vltr** [comment]
@Armanmd I use [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) with [bullet-train](https://github.com/caiogondim/bullet-train.zsh) theme (and a few custom options). Now it looks quite different than the screenshot I posted since I switched from terminator to tilix and created a material theme color scheme based on the Sublime Text [Material Theme](https://github.com/equinusocio/material-theme). I haven't changed it in a while now, so it may differs somehow ... I'll be glad to help if you have any questions :wink:

![screenshot from 2017-06-30 13-14-24](https://user-images.githubusercontent.com/1540275/27744624-98f902b6-5d96-11e7-9542-19b8e496a4cc.png)


@tista500 should we create a project | wiki for these customizations? Not only mine, of course, but people seems to have interest :metal:

**Comment by Armanmd** [comment]
@vltr How can I make a terminal like you?

**Comment by SolarLiner** [comment]
* `zsh` which is available pretty much everywhere
* `[oh_my_zsh](https://github.com/robbyrussell/oh-my-zsh)` a framework for zsh (others can be used but this one is complete IMHO)
* `[bullet-train](https://github.com/caiogondim/bullet-train.zsh)` which is the actual theme.

**Comment by Armanmd** [comment]
@SolarLiner use zsh with  theme [bullet-train.zsh](https://github.com/caiogondim/bullet-train.zsh)

**Comment by vltr** [comment]
@Armanmd quick question: do you use zsh with or without any framework?

**Comment by ArchangeGabriel** [comment]
JFYI, Firefox theming support has disappeared in Nightly, and they are no plans for rebuilding it currently. So all themes except for official ones are dead.

**Comment by vltr** [comment]
Thanks, @ArchangeGabriel ! Now that Mozilla have finally drawn that line, all we have to do is wait to see if anything pops up in the future regarding the "looks" of the newer versions of Firefox but, I have to say that version 57 doesn't look bad with the default theme from the start! At least, not in my opinion :wink:

![screenshot from 2017-08-13 14-14-26](https://user-images.githubusercontent.com/1540275/29251800-3c9169c8-8032-11e7-8f4d-b591753944a0.png)

![screenshot from 2017-08-13 14-13-57](https://user-images.githubusercontent.com/1540275/29251801-40a6ecc2-8032-11e7-97f3-68fdaa49b4ca.png)

Cheers!

**Comment by ArchangeGabriel** [comment]
Yes, I mostly agree with you, the default theme is quite nice, so this is not to much of an issue currently.

**Comment by ashkitten** [comment]
It would be nicer if text would actually show up where it's supposed to
![2017-08-13_15 49 52](https://user-images.githubusercontent.com/9281956/29252946-21b34f10-803f-11e7-82d0-d368e1fa76e8.png)

**Comment by vltr** [comment]
@ashkitten you're referring to the text in the address bar?

**Comment by ashkitten** [comment]
yes, it's the same color as the address bar

**Comment by vltr** [comment]
@ashkitten it looks alright in here. well, at least [firefox 57] is still in alpha stages :wink:

**Comment by cj-sv** [comment]
So far the current Firefox 57 on the official dark theme with Adapta looks really nice.

![image](https://user-images.githubusercontent.com/11567756/29269373-ab1291dc-8123-11e7-9667-883c6b5d28b9.png)

**Comment by tista500** [comment]
Currently close this, I may or may not re-open in future though.

Regards.

**Comment by ArchangeGabriel** [comment]
In the end Mozilla splitted density (Compact vs. Normal theme) and darkness (Default vs. Light/Dark themes).

So you can have any of the three densities (they’ve added “touch” along the way) with any of the darkness.

Default theme also matches colors from the system theme, which is the best I think. So I currently use compact mode, with default theme.
