### ISSUE TITLE
Adapta is not applied on ubuntu 18.04's System Monitor

### ISSUE THREAD

**Issue by pevoz23** [adapta-project/adapta-gtk-theme#695]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04 
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - GNOME Shell 3.28.1
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.1.14

**Related Application and/or Shell theming (or name of widget)**
System Monitor (v3.26.0)

**Actual issue**
System monitor's windows use Adwaita theme, when adapta is in use.

**Steps to reproduce (if you knew)**
Just set adapta theme as apllication theme in ubuntu 18.04

**Expected behaviour**
The obvious one.

**Other Note (feature-request, question, etc...)**
On ubuntu gnome 16.04.4 everything just worked fine. However, this seems to be related somehow to adapta and not to ubuntu, since other themes work fine.

See attached image
![screenshot from 2018-05-22 17-03-00](https://user-images.githubusercontent.com/18751893/40371750-739c1974-5de3-11e8-909e-fb15e9bc2b4e.png)

**Comment by HadrienPatte** [comment]
The issue seems to come from the fact that in ubuntu 18.04, `gnome-system-monitor` comes as a snap package by default. And snap packages no not seem to handle custom GTK themes well.
You can try installing the system monitor package through apt to get proper theming : 
```
# snap remove gnome-system-monitor
# apt install gnome-system-monitor
```
(`gnome-calculator` is in the same situation)
[source](https://github.com/ubuntu/gnome-shell-communitheme/issues/87)
