### ISSUE TITLE
Cinnamon alt-tab switcher thumbnails too small (theme issue)

### ISSUE THREAD

**Issue by memeplex** [adapta-project/adapta-gtk-theme#712]
```
Linux carlos 4.17.5-1-MANJARO #1 SMP PREEMPT Sun Jul 8 19:26:38 UTC 2018 x86_64 GNU/Linux

gtk3 3.22.30-1

Cinnamon 3.8.7

Display server protocol: X11

adapta-gtk-theme-3.94.0.1-1
```

In cinnamon alt-tab switcher configured with icons+thumbnails, thumbnails look too small. I've reported this to cinnamon tracker and they closed my report arguing it's a theme issue since it works fine with mint themes. I've since confirmed that the thumbnails are more reasonably sized with other cinnamon desktop themes. Notice that while my original report is for adapta maia variant I'm able to reproduce it using plain adapta. People at manjaro's gitlab suggested me to report this upstream, so here I am.

The original report: https://github.com/linuxmint/Cinnamon/issues/7739

Thread in manjaro's forum: https://forum.manjaro.org/t/manjaro-theme-not-playing-well-with-cinnamon-alt-tab-switcher/52301

The report in manjaro's gitlab: https://gitlab.manjaro.org/packages/community/themes/adapta-manjaro-themes/issues/1

Screenshot:

![screenshot from 2018-07-15 11-53-28](https://user-images.githubusercontent.com/2845433/42738252-068f86ce-8857-11e8-8aca-3b229841e5cc.png)

**Steps to reproduce (if you knew)**

Enter the Windows setting dialog, in Alt-Tab select Icons and thumbnails, open a window, press Alt-Tab wait for the thumbnail to open.

**Expected behaviour**

Thumbnail sized according to its container window.

**Comment by tista500** [comment]
When `org.cinnamon.desktop.interface scaling-factor` was set to `uint32 2` in Mint-Y:
![screenshot from 2018-07-19 12-07-36](https://user-images.githubusercontent.com/6073622/42919885-09ddd2a4-8b4f-11e8-81d7-2cf2bdbc3d33.png)

The selector `.switcher-list .thumbnail` defines the width/height of the container of an actual thumbnail instead of thumbnail ST texture itself. So I don't think that was theme issue.
