### ISSUE TITLE
New theme wtf ?

### ISSUE THREAD

**Issue by clintm90** [adapta-project/adapta-gtk-theme#741]
Hello,

i use adapta and it's a very good theme, but i have make my updates and the theme is fucking ugly

what is the reason ?

thanks

**Comment by Cypher1** [comment]
Bit rude mate. A reminder that @tista500 is doing this for free.

**Comment by cimarronline** [comment]
The maintainer just [reverted the recent changes and dropped this project](https://github.com/adapta-project/adapta-gtk-theme/blob/master/README.md). I'm starting to understand why...

**Comment by clintm90** [comment]
Yes it's true @Cypher1 i have make a fast issue, i'm sorry

**Comment by bilelmoussaoui** [comment]
@clintm90 It's not about a fast issue. It's about WORDING. Its' his own project, he does whatever he wants with it. You're free to fork it if you ever want to keep it the old way.

**Comment by benfeatherstone** [comment]
I'm actually a huge fan of the new theme. Has that new one found a new home so I can install it?

**Comment by cjdm** [comment]
I don't really know why the maintainer dropped the project, but I truly appreciate the effort of maintaining such a complete theme. I use Adapta since long ago, I saw a lot of changes, and I was very happy when Arch Linux included it on its community repo, since I'm one of those Arch users that prefer to keep at a minimum the use of AUR. After the last Adapta changes (v. 3.95.0), I really liked the new style, chiefly the Brila variant, it looks good on Gnome 3.30, and it has a lot of potential. People complaining about the new changes just had to fork the 3.94 version, or wait until someone else did it. Thanks @tista500 for all your work.

**Comment by clintm90** [comment]
I'm sorry for the 7 people that have reacted with :-1:  but it's pretty awful, i use Arch too and when i install a new computer i automatically install adapta because it was a very beautiful theme and when i've seen the update this morning it was puzzled.

BUT in fact it's not so uggly, it's just a little bit darker, but why not
![capture d ecran de 2018-10-03 23-54-25](https://user-images.githubusercontent.com/5221349/46441726-afcff300-c767-11e8-9aa2-8569be3cc869.png)

I just was surprised...
